// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFAqzlmkYadUxXAlZ8TXPp6ia0p19cLKQ',
    appId: '1:474613371614:android:5eaa93bd844e9f5cd5e84f',
    messagingSenderId: '474613371614',
    projectId: 'library-ai-73515',
    storageBucket: 'library-ai-73515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_GbtYSiBoXFfXsKeajb81nEjs8-EaS0Q',
    appId: '1:474613371614:ios:d18b133fefc7db42d5e84f',
    messagingSenderId: '474613371614',
    projectId: 'library-ai-73515',
    storageBucket: 'library-ai-73515.firebasestorage.app',
    androidClientId:
        '474613371614-aqjse77sgugok48f0g6rqtoj32e6vi80.apps.googleusercontent.com',
    iosClientId:
        '474613371614-cvei7voiqso5tv5ql9itco75aqvaeb0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryAi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBim2jYqfd28JDl1NZ_pYrnzlwu-YV8qw0',
    appId: '1:474613371614:web:583bfcb61cadbd03d5e84f',
    messagingSenderId: '474613371614',
    projectId: 'library-ai-73515',
    authDomain: 'library-ai-73515.firebaseapp.com',
    storageBucket: 'library-ai-73515.firebasestorage.app',
    measurementId: 'G-C2KHF4BF2C',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBim2jYqfd28JDl1NZ_pYrnzlwu-YV8qw0',
    appId: '1:474613371614:web:f54f49f287ac31b8d5e84f',
    messagingSenderId: '474613371614',
    projectId: 'library-ai-73515',
    authDomain: 'library-ai-73515.firebaseapp.com',
    storageBucket: 'library-ai-73515.firebasestorage.app',
    measurementId: 'G-WF6T24XFF7',
  );
}
